### ISSUE TITLE
Fix Game page "Submit" button and timer submit issue 

### ISSUE THREAD

**Issue by armsp** [sopra-fs23-group-15/envisage-client#102]
When we submit just within time, the dalle api call takes time to generate the image and meanwhile the auto-submission is also triggered and a second call to the same api in backend is made which causes some issues in the server. 
Make sure that either the Submit or the Auto Submit works and not both.

**Comment by marion-an** [comment]
04696e6988dbc774926e97bc1536c38ffc230449
