### ISSUE TITLE
Fix the timer pausing problem

### ISSUE THREAD

**Issue by xueswang** [sopra-fs23-group-15/envisage-client#105]

**Comment by armsp** [comment]
https://github.com/sopra-fs23-group-15/envisage-client/pull/135

**Comment by nikita-uzh** [comment]
https://github.com/sopra-fs23-group-15/envisage-client/pull/140/commits/ad41b3e2138b4babbeecbfbacaeaf739c9b9a347

**Comment by armsp** [comment]
https://github.com/sopra-fs23-group-15/envisage-client/commit/653e62af32f38ec027f8e541369261bd33d791e5 AND https://github.com/sopra-fs23-group-15/envisage-client/commit/a4dc7eb2498faa50aa79463624c0e5bbbfdcc737
