### ISSUE TITLE
User input validation - only numbers can be entered on the landing page in the gamepin field

### ISSUE THREAD

**Issue by armsp** [sopra-fs23-group-15/envisage-client#109]

**Comment by armsp** [comment]
https://github.com/sopra-fs23-group-15/envisage-client/pull/113

**Comment by nikita-uzh** [comment]
https://github.com/sopra-fs23-group-15/envisage-client/commit/f23118a84becfaadfbaa844a5c84b163490d1156

**Comment by armsp** [comment]
https://github.com/sopra-fs23-group-15/envisage-client/commit/c8c3698187c86719c91bd7aff997dac00e09e34d
