### ISSUE TITLE
Fix image selection for multiple blank images

### ISSUE THREAD

**Issue by armsp** [sopra-fs23-group-15/envisage-client#168]
When multiple users do not submit prompt, then selection selects all blank images
![Screenshot 2023-05-22 at 15-48-08 Envisage](https://github.com/sopra-fs23-group-15/envisage-client/assets/12681262/ed23d750-2910-464a-9923-5ffd16ab8eba)

**Comment by nikita-uzh** [comment]
https://github.com/sopra-fs23-group-15/envisage-client/commit/3b6633d4295ea8c8e8f73902c64e5549497b333a
